(function() {
  var template = Handlebars.template, templates = Handlebars.templates = Handlebars.templates || {};
templates['footer'] = template({"compiler":[6,">= 2.0.0-beta.1"],"main":function(depth0,helpers,partials,data) {
    var helper;

  return "<footer>\n  <p>"
    + this.escapeExpression(((helper = (helper = helpers.copyright || (depth0 != null ? depth0.copyright : depth0)) != null ? helper : helpers.helperMissing),(typeof helper === "function" ? helper.call(depth0,{"name":"copyright","hash":{},"data":data}) : helper)))
    + "</p>\n</footer>\n";
},"useData":true});
templates['header'] = template({"compiler":[6,">= 2.0.0-beta.1"],"main":function(depth0,helpers,partials,data) {
    var helper;

  return "<header>\n  <div class=\"container\">\n    <a href=\"/\" id=\"logo\"><img alt=\"Choice company driving car logo\" src=\""
    + this.escapeExpression(((helper = (helper = helpers.logo_file || (depth0 != null ? depth0.logo_file : depth0)) != null ? helper : helpers.helperMissing),(typeof helper === "function" ? helper.call(depth0,{"name":"logo_file","hash":{},"data":data}) : helper)))
    + "\" id=\"logo-image\"></a>\n    <ul class=\"navbar navbar-right nav\">\n      <li>\n        <!-- <a href=\"/merchants\" class=\"button\" id=\"merchant-button\">For Companies</a> -->\n      </li>\n    </ul>\n  </div>\n</header>\n";
},"useData":true});
templates['hero'] = template({"compiler":[6,">= 2.0.0-beta.1"],"main":function(depth0,helpers,partials,data) {
    return "<div class=\"jumbotron\" id=\"hero-section-jumbotron\">\n  <div class=\"container\" id=\"hero-section\">\n\n    <div class=\"row\">\n\n      <div class=\"col-md-7\" id=\"choice-description\">\n        <h1> Drive with Choice </h1>\n        <p> Earn up to $25 an hour, <span style=\"font-style: italics\"> even during off-peak times.</span> </p>\n        <p>Choice partners with multiple, hand-selected retailers to provide you with access more jobs, increased efficiency, and higher pay. </p>\n      </div>\n\n      <div class=\"col-md-4 col-md-offset-1\" id=\"form-container\">\n\n        <form>\n          <h2 id=\"cta\"> Start Driving </h2>\n          <p id=\"instructions\"> Enter your info, download the Choice App, and we will reach out to get you started! </p>\n\n          <div class=\"row\">\n            <div class=\"col-md-12\">\n              <input type=\"text\" class=\"form-control\" id=\"first-name-input\" placeholder=\"First\">\n            </div>\n          </div>\n\n          <div class=\"row\">\n            <div class=\"col-md-12\">\n              <input type=\"text\" class=\"form-control\" id=\"last-name-input\" placeholder=\"Last\">\n            </div>\n          </div>\n\n          <div class=\"row\">\n            <div class=\"col-md-12\">\n              <input type=\"text\" class=\"form-control\" id=\"email-input\" placeholder=\"Email\">\n            </div>\n          </div>\n\n          <div class=\"row\">\n            <div class=\"col-md-12\">\n              <input type=\"text\" class=\"form-control\" id=\"phone-number-input\" placeholder=\"Phone\">\n            </div>\n          </div>\n\n          <div class=\"row\">\n            <div class=\"col-md-12\">\n              <input type=\"text\" class=\"form-control\" id=\"city-input\" placeholder=\"City\">\n            </div>\n          </div>\n\n          <div id=\"form-status\"></div>\n          <a onclick=\"submit()\" class=\"button\" id=\"submit-button\">Apply Now</a>\n        </form>\n\n      </div>\n    </div>\n\n  </div>\n</div>\n";
},"useData":true});
templates['how_it_works'] = template({"compiler":[6,">= 2.0.0-beta.1"],"main":function(depth0,helpers,partials,data) {
    return "<div class=\"jumbotron\" id=\"how-it-works-container\">\n  <div class=\"container\">\n    <h2 class=\"section-header\"> How it Works </h2>\n    <div class=\"slider\">\n\n      <div id=\"slide1\">\n        <div class=\"row\">\n          <div class=\"col-md-3 col-md-offset-1\">\n            <img src=\"assets/images/pick_job.png\" height=\"500\" width=\"244\">\n          </div>\n          <div class=\"col-md-5 col-md-offset-1 col-xs-8 col-xs-offset-2 caption\">\n            <div class=\"how-it-works-text-wrapper\">\n              <h3>Pick your job</h3>\n              <p>A single package pickup, and multiple drop-off locations to minimize your time and maximize your earnings.</p>\n            </div>\n          </div>\n        </div>\n      </div>\n\n      <div id=\"slide2\">\n        <div class=\"row\">\n          <div class=\"col-md-3 col-md-offset-1\">\n            <img src=\"assets/images/follow_steps_choose_order.png\" height=\"500\" width=\"244\">\n          </div>\n          <div class=\"col-md-5 col-md-offset-1 col-xs-8 col-xs-offset-2 caption\">\n            <div class=\"how-it-works-text-wrapper\">\n              <h3>Simple steps, displayed clearly</h3>\n              <p>We give you a list of deliveries, you get to choose the best order to do them in.</p>\n            </div>\n          </div>\n        </div>\n      </div>\n\n      <div id=\"slide3\">\n        <div class=\"row\">\n          <div class=\"col-md-3 col-md-offset-1\">\n            <img src=\"assets/images/ext_nav_opt.png\" height=\"500\" width=\"244\">\n          </div>\n          <div class=\"col-md-5 col-md-offset-1 col-xs-8 col-xs-offset-2 caption\">\n            <div class=\"how-it-works-text-wrapper\">\n              <h3>Navigate with ease</h3>\n              <p>The Choice app will direct you right to your delivery, or let you use your favourite navigation app.</p>\n            </div>\n          </div>\n        </div>\n      </div>\n\n    </div>\n  </div>\n</div>\n";
},"useData":true});
templates['why_choice'] = template({"compiler":[6,">= 2.0.0-beta.1"],"main":function(depth0,helpers,partials,data) {
    return "<div class=\"jumbotron\">\n  <div class=\"container\" id=\"why-choice-container\">\n    <div class=\"row\">\n      <h2 class=\"section-header\"> On Demand the way it should have been. </h2>\n\n      <div class=\"col-md-4 col-md-offset-0 col-sm-8 col-sm-offset-2\">\n        <img src=\"assets/images/connections-128.png\">\n        <h3>Access to More Jobs</h3>\n        <p> Don&#39;t be tied to one provider&#39;s. &#32; Choose from a variety of well-paying jobs throughout the day &#8212; all on one platform.</p>\n      </div>\n\n      <div class=\"col-md-4 col-md-offset-0 col-sm-8 col-sm-offset-2\">\n        <img src=\"assets/images/agile_flexible_planning-128.png\">\n        <h3>Eliminate Slow Times</h3>\n        <p> No more sitting around idle during the midday slump. &#32; Make the most of your time, any time of the day.  </p>\n      </div>\n\n      <div class=\"col-md-4 col-md-offset-0 col-sm-8 col-sm-offset-2\">\n        <img src=\"assets/images/agile_sprint_goal-128.png\">\n        <h3>Truly Flexible Schedules</h3>\n        <p> &#34;Work when you want&#34; became &#34;work when there&#39;s work.&#34; With Choice, regain control with predictable schedules. </p>\n      </div>\n\n    </div>\n  </div>\n</div>\n";
},"useData":true});
})();